### PR TITLE
Rewrite in TypeScript

### PR DESCRIPTION
**Pull request by lierdakil**
Adds a bunch of tests and lints related to that. Adds automatic
prettifying. Adds Travis-CI script.

Motivation: generally easier to maintain and CoffeeScript is practically dead. Also, I was bored and at the moment this seemed like a reasonable thing to occupy myself with. Your call if you want to use this, release process is somewhat more complicated, considering you *have* to build (`npm run build`) before pushing, although that's nothing a precommit hook can't fix.

### CODE REVIEW

**Comment by fcrespo82** [comment]
Sorry for the late response.

I find this very useful. I'll try it in my system and maybe we change the master branch to this one.

Thank you very much for supporting and helping in this development.

**Comment by fcrespo82** [comment]
I liked the update, how you think we should insert this in our development plan?
Turn this into the master branch and put a pre-commit hook to not forget the `npm run build`, or some other type of automation?

**Comment by lierdakil** [comment]
> Turn this into the master branch and put a pre-commit hook to not forget the npm run build

That's pretty much what I do with my other projects, except I use [atom-typescript](https://github.com/TypeStrong/atom-typescript/), so running `npm run build` is seldom necessary, and I actually *don't* have it in precommit hook (although I probably should)

I don't think there's a lot of other options. There's also <https://www.npmjs.com/package/atom-ts-transpiler>, but users would have to install TypeScript as a dependency, and it isn't small.

**Comment by fcrespo82** [comment]
Ok, I’ll do that this week. Probably tomorrow but can’t promise. Thank you very much for helping with this little project.

**Pull request merged**
