### PR TITLE
Changed how editor is obtained and added a error message in case it fail

### PR DESCRIPTION
**Pull request by fcrespo82**
Could reproduce #44 and fixed.

Can you review the code please?

### CODE REVIEW

**Comment by lierdakil** [comment]
No-no, `atom.workspace.getActiveTextEditor` is a bad idea, it can lead to all kinds of issues. Problem is, editor that generated an error isn't necessarily active when event handler is called.

Changing `target` to `currentTarget` should work.

**Comment by lierdakil** [comment]
See 50e8ee086c5b2c57e92d41df51514e5ad80e2834 (also removed `editor` null/undefined check, since events are bound to `atom-text-editor`, which `currentTarget` is pretty much guaranteed to point to)

**Comment by fcrespo82** [comment]
Oh, ok. Didn’t thought about that!

Thanks for the correction. Will merge and publish  tomorrow. Out for the day.

**Comment by fcrespo82** [comment]
Closed due to better handling by @lierdakil in PR 46

**Pull request closed without merging**
