### PR TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### PR DESCRIPTION
**Pull request by liongmagezi**
Hi,
I really like this creation, it's very helpful when I writing Markdown.But I find some problem, if a cell not contains alphabet,i mean some chinese characters,will get a error in Atom.So I changed some code, and it is worked in my Atom. 
However I am a newcomer of CofeeScript, if you have better way to fix this error I wait in hope for your update. `: )` 
- A little bug
When a cell contains only analphabetic characters will get error of
length:
> Uncaught TypeError: Cannot read property 'length' of undefined

- Change Default alignment to Centre
  It just personal property.

### CODE REVIEW

**Comment by fcrespo82** [comment]
What you guys think about /[|:-]{2,}/ to find the format row? tested with some tables and seems to work. https://regex101.com/r/xI4dY7/1
Hit me with test tables so we can make it better.

**Comment by lierdakil** [comment]
@fcrespo82 
First, space is a valid symbol in format row (but only surrounding pipes). See examples at https://michelf.ca/projects/php-markdown/extra/#table
Second, suggested regex will match partial rows, like
| This is::    | not format row | <-- will match here
| ------------ | -------------- |
| Random Table | Test column    |

A little better version would be https://regex101.com/r/zT6vY4/1#javascript

It would still, however, match invalid format rows like this:
outro
:-:
teste
(according to spec, format row has to include at least one pipe)
or this:
| outro |
| :-:-:    |
| teste |
(according to spec, colons can only be placed at ends of separator cell)
see link for more examples of invalid matches

https://regex101.com/r/yR7xZ9/5#javascript would be more involved version, which, to my knowledge, should match strictly according to spec (i.e. either have leading and trailing pipes and have single column, OR have multiple columns, optionally with BOTH leading and trailing pipes, and only have column on sides of cell, NOT in the middle) But such regex is a terrible pain to maintain.

Personally, I would go with latter option, since I'm ok with terribly complicated regular expressions. But former would probably work for most use-cases.

**Comment by fcrespo82** [comment]
Yep, after I said that I realized that is no good. I will do my homework and study the markdown extra specification and use as the implementation. But I can only do that tomorrow. Please keep the bugs and enhancements coming! Thank you all for the help!Sent using CloudMagicOn qui, jan 8, 2015 at 7:45 PM,  Nikolay Yakimov <notifications@github.com> wrote:            @fcrespo82 
First, space is a valid symbol in format row (but only surrounding pipes). See examples at https://michelf.ca/projects/php-markdown/extra/#table
Second, suggested regex will match partial rows, like
| This is::    | not format row | <-- will match here
| ------------ | -------------- |
| Random Table | Test column    |

A little better version would be https://regex101.com/r/zT6vY4/1#javascript

It would still, however, match invalid format rows like this:
outro
:-:
teste
(according to spec, format row has to include at least one pipe)
or this:
| outro |
| :-:-:    |
| teste |
(according to spec, colons can only be placed at ends of separator cell)
see link for more examples of invalid matches

https://regex101.com/r/yR7xZ9/5#javascript would be more involved version, which, to my knowledge, should match strictly according to spec (i.e. either have leading and trailing pipes and have single column, OR have multiple columns, optionally with BOTH leading and trailing pipes, and only have column on sides of cell, NOT in the middle) But such regex is a terrible pain to maintain.

Personally, I would go with latter option, since I'm ok with terribly complicated regular expressions. But former would probably work for most use-cases.

**Comment by fcrespo82** [comment]
I'm more inclined to go with fixed position.

    formatline = lines[1]
    formatrow = 1
    lines.splice(1,1)

 I don't think there is any advantage in doing it dinamically since

> second line contains a mandatory separator line between the headers and the content; 

I only missing one edge case:

    |other
    |-
    |test

My code doesn't identify this as a valid table but it is valid as the documentation points

> Note: A table need at least one pipe on each line for Markdown Extra to parse it correctly. This means that the only way to create a one-column table is to add a leading or a tailing pipe, or both of them, to each line.

I've updated my regex to find all tables in a complex document here https://regex101.com/r/xI4dY7/2 if one of you can tweak it to identify the edge case I'll be very thankful

**Comment by lierdakil** [comment]
Some parsers, namely kramdown and pandoc, allow omission of header row. Granted, vanilla Markdown Extra does not.
I've updated regex to handle edge cases (additionally, I messed around with [:|-]+ a little to match spec more closely, made all groups non-capturing and removed extranneous match and character groups and removed m modifier as obsolete, since newlines are matched explicitly): https://regex101.com/r/xI4dY7/6
There are, however, some caveats, i.e. some malformed tables, such as
| | |
||-|
| | |
will be matched as well. I don't suppose it's a big deal, and I am bound by capabilities of native javascript regex. I could conceivably extend it to handle these cases as well, but that would increase code at least twofold, and it's big enough as is. 
Alternatives would be using external library like xregex, which could dramatically simplify writing complex regexes, or implementing a proper markdown parser (at least partially)

**Comment by lierdakil** [comment]
Okay, I've had a little more time with this and I think I nailed it. https://regex101.com/r/xI4dY7/7
This will match almost properly against everything I thought about throwing at it. Only case it handles not as reference implementation is rows consisting of single pipe (optionally surrounded by whitespace). Reference implementation silently ignores such rows.
Latest version also handles tables with omitted header (can be disabled by removing last ? in first capture group) and extracts table header as \1 (if not present, \1 is empty), format row as \2 and table body as \3. This could be used instead of hardcoding formatline = lines[1].

**Comment by lierdakil** [comment]
Ok. Please see 08374da6c9ec2bb35d35bc666c0408929448fe37 -- this should give a general idea on how I think this could be implemented. I'm notably bad with coffeescript though, so please feel free to change things around.

**Comment by fcrespo82** [comment]
Just publish an update with lierdakil@08374da6c9ec2bb35d35bc666c0408929448fe37 with updated regex.

I think you'll both enjoy it.

Thanks again for the tips.

**Comment by lierdakil** [comment]
That's great, thanks!

**Pull request closed without merging**
